name: viva_network_kit
description: A lightweight and developer-friendly network manager for Flutter, built on Dio, with automatic connectivity checks before every API request.
version: 2.1.8
homepage: https://vivasoftltd.com/
repository: https://github.com/vivasoft-ltd/flutter-network-kit
publish_to: pub.dev
issue_tracker: https://github.com/vivasoft-ltd/flutter-network-kit/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  dartz: ^0.10.1
  built_value: ^8.9.5
  connectivity_plus: ^6.1.3
  get_it: ^8.0.3
  built_collection: ^5.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

topics:
  - network_client
  - dio
  - http
  - connectivity_plus


